services:
  # Gluetun - VPN Client for Docker Containers
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    entrypoint: ["/scripts/secrets_loader.sh", "/gluetun-entrypoint"]
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["core", "all"]
    networks:
      - reverse_proxy
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    volumes:
      - $DOCKERDIR/scripts:/scripts:ro
      - $DOCKERDIR/appdata/gluetun:/gluetun
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
      VPN_SERVICE_PROVIDER: $VPN_SERVICE_PROVIDER
      VPN_TYPE: wireguard
      WIREGUARD_PRESHARED_KEY_FILE: /run/secrets/wireguard_preshared_key
      WIREGUARD_PRIVATE_KEY_FILE: /run/secrets/wireguard_private_key
      WIREGUARD_ADDRESSES: $WIREGUARD_ADDRESSES
      SERVER_REGIONS: $SERVER_REGIONS
      FIREWALL_VPN_INPUT_PORTS: $TORRENTING_PORT
    secrets:
      - wireguard_preshared_key
      - wireguard_private_key
    labels:
      ### Traefik
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.gluetun-qbittorrent-rtr.entrypoints=websecure"
      - "traefik.http.routers.gluetun-qbittorrent-rtr.rule=Host(`qbit.$DOMAINNAME`)"
      # Middlewares
      - "traefik.http.routers.gluetun-qbittorrent-rtr.middlewares=chain-oauth@file"
      # HTTP Services
      - "traefik.http.routers.gluetun-qbittorrent-rtr.service=gluetun-svc"
      - "traefik.http.services.gluetun-svc.loadbalancer.server.port=8080"
      ### Homepage
      - "homepage.group=Core"
      - "homepage.name=Gluetun"
      - "homepage.icon=gluetun.png"
      - "homepage.description=VPN Client for Docker Containers"
      - "homepage.widget.type=gluetun"
      - "homepage.widget.url=http://gluetun:8000"
