services:
  # OAuth - Single Sign On using OAuth 2.0
  oauth:
    container_name: oauth
    image: thomseddon/traefik-forward-auth:latest
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["core", "all"]
    networks:
      - t2_proxy
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
      CONFIG: /config
      COOKIE_DOMAIN: $DOMAINNAME
      INSECURE_COOKIE: false
      AUTH_HOST: oauth.$DOMAINNAME
      URL_PATH: /_oauth
      LOG_LEVEL: warn # set to trace while testing bypass rules
      LOG_FORMAT: text
      LIFETIME: 86400 # 1 day
      DEFAULT_ACTION: auth
      DEFAULT_PROVIDER: google
    secrets:
      - source: traefik_forward_auth
        target: /config
    labels:
      ### Traefik
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.oauth-rtr.tls=true"
      - "traefik.http.routers.oauth-rtr.entrypoints=websecure"
      - "traefik.http.routers.oauth-rtr.rule=Host(`oauth.$DOMAINNAME`)"
      # Middlewares
      - "traefik.http.routers.oauth-rtr.middlewares=chain-oauth@file"
      # HTTP Services
      - "traefik.http.routers.oauth-rtr.service=oauth-svc"
      - "traefik.http.services.oauth-svc.loadbalancer.server.port=4181"
      ### Homepage
      - "homepage.group=Core"
      - "homepage.name=OAuth"
      - "homepage.icon=google.png"
      - "homepage.description=Single Sign On using OAuth 2.0"
