services:
  # Jellyfin - Media Server
  jellyfin:
    # image: jellyfin/jellyfin:latest
    image: ghcr.io/endrl/jellyfin:latest # Custom Jellyfin image with patch for segment skipping
    container_name: jellyfin
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["apps", "media", "all"]
    networks:
      - t2_proxy
    devices:
      - /dev/dri:/dev/dri # for harware transcoding
    volumes:
      - $DOCKERDIR/appdata/jellyfin:/config
      - $DOCKERDIR/data/media:/data/media
      - /dev/shm:/data/transcode
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
      UMASK_SET: 022
    labels:
      ### Traefik
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.jellyfin-rtr.entrypoints=websecure"
      - "traefik.http.routers.jellyfin-rtr.rule=Host(`jellyfin.$DOMAINNAME`)"
      # Middlewares
      - "traefik.http.routers.jellyfin-rtr.middlewares=chain-no-auth@file"
      # HTTP Services
      - "traefik.http.routers.jellyfin-rtr.service=jellyfin-svc"
      - "traefik.http.services.jellyfin-svc.loadbalancer.server.port=8096"
      ### Homepage
      - "homepage.group=Media"
      - "homepage.name=Jellyfin"
      - "homepage.icon=jellyfin.png"
      - "homepage.href=https://jellyfin.$DOMAINNAME"
      - "homepage.description=Media Server"
      - "homepage.widget.type=jellyfin"
      - "homepage.widget.url=http://jellyfin:8096"
      - "homepage.widget.key={{HOMEPAGE_FILE_JELLYFIN_KEY}}"
      - "homepage.widget.enableBlocks=true"
      - 'homepage.widget.fields=["movies","series","episodes"]'
