services:
  # Radarr - Movie management
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["apps", "media", "all"]
    networks:
      - t2_proxy
    volumes:
      - $DOCKERDIR/appdata/radarr:/config
      - $DOCKERDIR/data:/data
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
    labels:
      ### Traefik
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.radarr-rtr.entrypoints=websecure"
      - "traefik.http.routers.radarr-rtr.rule=Host(`radarr.$DOMAINNAME`)"
      # Middlewares
      - "traefik.http.routers.radarr-rtr.middlewares=chain-oauth@file"
      # HTTP Services
      - "traefik.http.routers.radarr-rtr.service=radarr-svc"
      - "traefik.http.services.radarr-svc.loadbalancer.server.port=7878"
      ### Homepage
      - "homepage.group=Media"
      - "homepage.name=Radarr"
      - "homepage.icon=radarr.png"
      - "homepage.href=https://radarr.$DOMAINNAME"
      - "homepage.description=Movie Management"
      - "homepage.widget.type=radarr"
      - "homepage.widget.url=http://radarr:7878"
      - "homepage.widget.key={{HOMEPAGE_FILE_RADARR_KEY}}"
      - "homepage.widget.enableQueue=true"
