services:
  # Bazarr - Subtitle Management
  bazarr:
    image: lscr.io/linuxserver/bazarr
    container_name: bazarr
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["apps", "complementary", "all"]
    networks:
      - t2_proxy
    volumes:
      - $DOCKERDIR/appdata/bazarr:/config
      - $DOCKERDIR/data/media:/data/media
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
    labels:
      ### Traefik
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.bazarr-rtr.entrypoints=websecure"
      - "traefik.http.routers.bazarr-rtr.rule=Host(`bazarr.$DOMAINNAME`)"
      # Middlewares
      - "traefik.http.routers.bazarr-rtr.middlewares=chain-oauth@file"
      # HTTP Services
      - "traefik.http.routers.bazarr-rtr.service=bazarr-svc"
      - "traefik.http.services.bazarr-svc.loadbalancer.server.port=6767"
      ### Homepage
      - "homepage.group=Complementary"
      - "homepage.name=Bazarr"
      - "homepage.icon=bazarr.png"
      - "homepage.href=https://bazarr.$DOMAINNAME"
      - "homepage.description=Subtitle Management"
      - "homepage.widget.type=bazarr"
      - "homepage.widget.url=http://bazarr:6767"
      - "homepage.widget.key={{HOMEPAGE_FILE_BAZARR_KEY}}"
