services:
  # Notifiarr - Client for Notifiarr.com
  notifiarr:
    image: ghcr.io/notifiarr/notifiarr:unstable-alpine
    container_name: notifiarr
    entrypoint: ["/scripts/secrets_loader.sh", "/notifiarr"]
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["apps", "complementary", "all"]
    networks:
      - reverse_proxy
    volumes:
      - /var/run/utmp:/var/run/utmp
      - /etc/machine-id:/etc/machine-id
      - $DOCKERDIR/scripts:/scripts:ro
      - $DOCKERDIR/appdata/notifiarr:/config
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
      DN_API_KEY_FILE: /run/secrets/notifiarr_key
      DN_AUTO_UPDATE: off
      DN_PROWLARR_0_NAME: Prowlarr
      DN_PROWLARR_0_URL: http://prowlarr:9696
      DN_PROWLARR_0_API_KEY_FILE: /run/secrets/prowlarr_key
      DN_RADARR_0_NAME: Radarr
      DN_RADARR_0_URL: http://radarr:7878
      DN_RADARR_0_API_KEY_FILE: /run/secrets/radarr_key
      DN_SONARR_0_NAME: Sonarr
      DN_SONARR_0_URL: http://sonarr:8989
      DN_SONARR_0_API_KEY_FILE: /run/secrets/sonarr_key
      DN_QBIT_0_NAME: qBittorrent
      DN_QBIT_0_URL: http://gluetun:8080
    secrets:
      - notifiarr_key
      - prowlarr_key
      - radarr_key
      - sonarr_key
    labels:
      ### Traefik
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.notifiarr-rtr.entrypoints=websecure"
      - "traefik.http.routers.notifiarr-rtr.rule=Host(`notifiarr.$DOMAINNAME`)"
      # Middlewares
      - "traefik.http.routers.notifiarr-rtr.middlewares=chain-oauth@file"
      # HTTP Services
      - "traefik.http.routers.notifiarr-rtr.service=notifiarr-svc"
      - "traefik.http.services.notifiarr-svc.loadbalancer.server.port=5454"
      ### Homepage
      - "homepage.group=Complementary"
      - "homepage.name=Notifiarr"
      - "homepage.icon=notifiarr.png"
      - "homepage.href=https://notifiarr.$DOMAINNAME"
      - "homepage.description=Client for Notifiarr.com"
