services:
  # Prowlarr - Torrent proxy
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["apps", "complementary", "all"]
    networks:
      - reverse_proxy
    volumes:
      - $DOCKERDIR/appdata/prowlarr:/config
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
    labels:
      ### Traefik
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.prowlarr-rtr.entrypoints=websecure"
      - "traefik.http.routers.prowlarr-rtr.rule=Host(`prowlarr.$DOMAINNAME`)"
      # Middlewares
      - "traefik.http.routers.prowlarr-rtr.middlewares=chain-oauth@file"
      # HTTP Services
      - "traefik.http.routers.prowlarr-rtr.service=prowlarr-svc"
      - "traefik.http.services.prowlarr-svc.loadbalancer.server.port=9696"
      ### Homepage
      - "homepage.group=Complementary"
      - "homepage.name=Prowlarr"
      - "homepage.icon=prowlarr.png"
      - "homepage.href=https://prowlarr.$DOMAINNAME"
      - "homepage.description=Torrent proxy"
      - "homepage.widget.type=prowlarr"
      - "homepage.widget.url=http://prowlarr:9696"
      - "homepage.widget.key={{HOMEPAGE_FILE_PROWLARR_KEY}}"
