services:
  # Dockge - Docker Compose Manager
  dockge:
    image: louislam/dockge
    container_name: dockge
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["apps", "admin", "all"]
    networks:
      - t2_proxy
      - socket_proxy
    volumes:
      - $DOCKERDIR/appdata/dockge/data:/app/data
      - $DOCKERDIR/appdata/dockge/stacks:/opt/stacks
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
      DOMAINNAME: $DOMAINNAME
      DOCKER_HOST: tcp://socket-proxy:2375
    labels:
      ### Traefik
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.dockge-rtr.entrypoints=websecure"
      - "traefik.http.routers.dockge-rtr.rule=Host(`dockge.$DOMAINNAME`)"
      # Middlewares
      - "traefik.http.routers.dockge-rtr.middlewares=chain-oauth@file"
      # HTTP Services
      - "traefik.http.routers.dockge-rtr.service=dockge-svc"
      - "traefik.http.services.dockge-svc.loadbalancer.server.port=5001"
      ### Homepage
      - "homepage.group=Admin"
      - "homepage.name=Dockge"
      - "homepage.icon=dockge.png"
      - "homepage.href=https://dockge.$DOMAINNAME"
      - "homepage.description=Docker Compose Manager"
