services:
  # Dozzle - Real-time Docker Log Viewer
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["apps", "admin", "all"]
    networks:
      - t2_proxy
      - socket_proxy
    environment:
      DOZZLE_LEVEL: info
      DOZZLE_TAILSIZE: 300
      DOZZLE_FILTER: "status=running"
      # DOZZLE_FILTER: "label=log_me" # limits logs displayed to containers with this label
      DOCKER_HOST: tcp://socket-proxy:2375
    labels:
      ### Traefik
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.dozzle-rtr.entrypoints=websecure"
      - "traefik.http.routers.dozzle-rtr.rule=Host(`dozzle.$DOMAINNAME`)"
      # Middlewares
      - "traefik.http.routers.dozzle-rtr.middlewares=chain-oauth@file"
      # HTTP Services
      - "traefik.http.routers.dozzle-rtr.service=dozzle-svc"
      - "traefik.http.services.dozzle-svc.loadbalancer.server.port=8080"
      ### Homepage
      - "homepage.group=Admin"
      - "homepage.name=Dozzle"
      - "homepage.icon=dozzle.png"
      - "homepage.href=https://dozzle.$DOMAINNAME"
      - "homepage.description=Real-time Docker Log Viewer"
