services:
  # Docker-GC - Automatic Docker Garbage Collection
  docker-gc:
    image: clockworksoul/docker-gc-cron:latest
    container_name: docker-gc
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["apps", "maintenance", "all"]
    networks:
      - socket_proxy
    volumes:
      - $DOCKERDIR/appdata/docker-gc/docker-gc-exclude:/etc/docker-gc-exclude
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
      CRON: 0 0 1 * * ? # Everyday at 1am.
      FORCE_IMAGE_REMOVAL: 1
      FORCE_CONTAINER_REMOVAL: 0
      GRACE_PERIOD_SECONDS: 604800
      DRY_RUN: 0
      CLEAN_UP_VOLUMES: 1
      DOCKER_HOST: tcp://socket-proxy:2375
    labels:
      ### Homepage
      - "homepage.group=Maintenance"
      - "homepage.name=Docker-GC"
      - "homepage.icon=mdi-delete"
      - "homepage.description=Automatic Docker Garbage Collection"
